// generated by makecode.pl
#ifndef DBUSTESTINTERFACE_H
#define DBUSTESTINTERFACE_H
#include "dbusobjectinterface.h"
#include <map>
class TestInterface;
class DBusTestInterface : public DBusObjectInterface {
private:
    typedef void (DBusTestInterface::*handlerFunction)
        (DBusMessage* msg, DBusConnection* conn);
    TestInterface* impl;
    std::map<std::string, handlerFunction> handlers;
    DBusHandlerResult handleCall(DBusConnection* connection, DBusMessage* msg);
    void upload(DBusMessage* msg, DBusConnection* conn);
    void concat(DBusMessage* msg, DBusConnection* conn);
    void helloWorld(DBusMessage* msg, DBusConnection* conn);
    void giveMap(DBusMessage* msg, DBusConnection* conn);
public:
    DBusTestInterface(TestInterface* i);
    ~DBusTestInterface() {}
    std::string getIntrospectionXML();
};
#endif
