/* config.h. Generated by cmake from config.h.cmake */

#ifdef _WIN32
#define PATH_SEPARATOR ";"
#else
#define PATH_SEPARATOR ":"
#endif

#ifndef CONFIG_H
#define CONFIG_H

#define LIBINSTALLDIR "${LIB_DESTINATION}"

#define SOURCEDIR "${CMAKE_CURRENT_SOURCE_DIR}"

#define BINARYDIR "${CMAKE_CURRENT_BINARY_DIR}"

#define INSTALLDIR "${CMAKE_INSTALL_PREFIX}"

#define MIMEINSTALLDIR "${MIMEINSTALLDIR}"

#endif //CONFIG_H
